### ISSUE TITLE
NPM Install errors

### ISSUE THREAD

**Issue by Alexis-Chalix** [gwenf/vue3-fcc-course-basic-product-cart-demo#5]
Hello,

I tried doing an npm install to follow the course but I'm getting errors, you can find the error log below :
[2021-10-13T08_11_03_763Z-debug.log](https://github.com/gwenf/vue3-fcc-course-basic-product-cart-demo/files/7336259/2021-10-13T08_11_03_763Z-debug.log)

As I see it says that it can't find python because it's not in my Path ... but it is, so I'm quite confused on what to do. As I check the comment on the video, I'm not the only one running onto that issue.

**Comment by gwenf** [comment]
I think this is resolved with: https://github.com/gwenf/vue3-fcc-course-basic-product-cart-demo/issues/8
