### ISSUE TITLE
NPM install errors (OS:Windows 8.1, Node.js version:8.1.2, IDE: Visual Studio Code )

### ISSUE THREAD

**Issue by smttkin** [gwenf/vue3-fcc-course-basic-product-cart-demo#8]
### **_I solved it. The problem is about the version of modules under the devDependicies object in the package.json file._**

1. Delete the package-lock.json file
2. Change versions of modules to "latest" in the devDependicies object (look for package.json)
3. Write the code that is in below to terminal or what you use for this
 "npm install" ->That code uses is installing a specific version of modules that in dependencies **_(dependencies are modules that are stated in the "devDependencies" object that in the "package.json" file)_**
4. Finally, you can start this project with;
 "npm start"

**Comment by smttkin** [comment]
It works with a newer version of Node.js. The version is 8.1.2

**Comment by smttkin** [comment]
I guess the main problem is about the lock file. The warn messages to tell this at least

**Comment by smttkin** [comment]
And module versions are a big problem too

**Comment by smttkin** [comment]
**_I solved it. The problem is about the version of modules under the devDependicies object in the package.json file._** 


1. Delete the package-lock.json file
2. Change versions of modules to "latest" in the devDependicies object (look for package.json)
3. Write the code that is in below to terminal or what you use for this
"npm install" ->That code uses is installing a specific version of modules that in dependencies _(dependencies are modules that are stated in the "devDependencies" object that in the "package.json" file)_
4. Finally, you can start this project with;
"npm start"

**Comment by smttkin** [comment]
> I will try to use older versions of Node.js to fix the issue.

Didn't work

**Comment by rosmis** [comment]
Thank you so much for the tip. I was stuck on these npm install errors since this morning and your tips fixed the issue. Thanks

**Comment by smttkin** [comment]
> Thank you so much for the tip. I was stuck on these npm install errors since this morning and your tips fixed the issue. Thanks

You're welcome, I am happy to that i could help you :)
